import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.join(import.meta.dir, "../..");
const MATRIX_PATH = path.join(
  ROOT,
  "design/generated/matrices/dialog-color-picker.json"
);
const CSS_OUT = path.join(ROOT, "public/picto-ds/picto-ds.css");
const COMPONENTS_OUT = path.join(ROOT, "design/generated/components.html");

/** Chrome / neutral colors excluded from the 16 UI swatch variables. */
const CHROME_COLORS = new Set([
  "#ffffff",
  "#aaaaaa",
  "#929292",
  "#fbfbfb",
  "#000000",
  "#1a1a1e",
]);

interface MatrixFile {
  palette: string[];
}

const matrix = JSON.parse(await readFile(MATRIX_PATH, "utf-8")) as MatrixFile;
const swatchColors = matrix.palette
  .map((color) => color.toLowerCase())
  .filter((color) => !CHROME_COLORS.has(color))
  .slice(0, 16);

if (swatchColors.length !== 16) {
  throw new Error(
    `Expected 16 swatch colors, got ${swatchColors.length} from dialog-color-picker palette`
  );
}

const swatchVars = swatchColors
  .map(
    (color, index) =>
      `  --picto-ui-${String(index + 1).padStart(2, "0")}: ${color};`
  )
  .join("\n");

const css = `/* picto-ds.css v0 — generated by tools/sprites/generate-css.ts */
.picto-ds {
  --picto-scale: 2;
  --picto-ink: #1a1a1e;
  --picto-paper: #fbfbfb;
  --picto-chrome-gray: #aaaaaa;
${swatchVars}
  box-sizing: border-box;
  font-family: monospace;
  color: var(--picto-ink);
}

.picto-ds *,
.picto-ds *::before,
.picto-ds *::after {
  box-sizing: border-box;
}

/* DS shell: two 256×192 screens stacked, scaled crisp */
.picto-ds .picto-shell-frame {
  width: calc(256px * var(--picto-scale));
  height: calc(384px * var(--picto-scale));
}

.picto-ds .picto-shell {
  width: 256px;
  height: 384px;
  display: flex;
  flex-direction: column;
  transform: scale(var(--picto-scale));
  transform-origin: top left;
  image-rendering: pixelated;
}

.picto-ds .picto-shell img {
  image-rendering: pixelated;
  display: block;
  pointer-events: none;
  user-select: none;
  -webkit-user-drag: none;
}

/* Top screen */
.picto-ds .picto-screen-top {
  position: relative;
  width: 256px;
  height: 192px;
  overflow: hidden;
  background: var(--picto-paper);
}

.picto-ds .picto-screen-top > .picto-screen-bg {
  position: absolute;
  inset: 0;
}

.picto-ds .picto-logo-bar {
  position: absolute;
  top: 8px;
  left: 11px;
}

.picto-ds .picto-entering-banner {
  position: absolute;
  top: 38px;
  left: 9px;
}

.picto-ds .picto-author-input {
  position: absolute;
  top: 42px;
  left: 118px;
  width: 120px;
  height: 14px;
  padding: 0 4px;
  border: none;
  background: transparent;
  font: 8px/14px monospace;
  color: var(--picto-ink);
  outline: none;
  z-index: 2;
}

.picto-ds .picto-author-input::placeholder {
  color: var(--picto-chrome-gray);
}

.picto-ds .picto-message-list {
  position: absolute;
  top: 68px;
  left: 11px;
  right: 11px;
  bottom: 4px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 6px;
  scrollbar-width: thin;
}

/* Message card — CSS recreation (redistributable) */
.picto-ds .picto-message-card {
  position: relative;
  width: 234px;
  min-height: 103px;
  flex-shrink: 0;
  background: var(--picto-paper);
  border: 1px solid #494949;
  border-radius: 4px;
  animation: picto-card-in 0.35s ease-out;
}

@keyframes picto-card-in {
  from {
    opacity: 0;
    transform: translateY(-8px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.picto-ds .picto-nametag {
  position: absolute;
  top: -1px;
  left: -1px;
  width: 64px;
  height: 22px;
}

.picto-ds .picto-nametag > img {
  display: block;
  width: 64px;
  height: 22px;
}

.picto-ds .picto-nametag-text {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 8px;
  line-height: 1;
  color: var(--picto-paper);
  text-align: center;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  padding: 0 4px;
  pointer-events: none;
}

.picto-ds .picto-message-preview {
  position: absolute;
  left: 2px;
  top: 22px;
  width: 228px;
  height: 79px;
  image-rendering: pixelated;
  pointer-events: none;
}

/* Bottom screen — composer */
.picto-ds .picto-composer {
  position: relative;
  width: 256px;
  height: 192px;
  overflow: hidden;
  border-top: 4px solid var(--picto-ink);
}

.picto-ds .picto-composer > .picto-composer-bg {
  position: absolute;
  inset: 0;
}

.picto-ds .picto-canvas {
  position: absolute;
  left: 24px;
  top: 18px;
  width: 228px;
  height: 79px;
  cursor: crosshair;
  touch-action: none;
  z-index: 1;
}

.picto-ds .picto-keyboard {
  position: absolute;
  left: 22px;
  top: 104px;
}

/* SEND hit area — measured against composer-chrome-default */
.picto-ds .picto-send-zone {
  position: absolute;
  left: 224px;
  top: 104px;
  width: 30px;
  height: 37px;
  padding: 0;
  border: none;
  background: transparent;
  cursor: pointer;
  z-index: 2;
}

.picto-ds .picto-send-zone:focus-visible {
  outline: 2px solid var(--picto-ui-03);
  outline-offset: 1px;
}

/* Basic button + statusbar recreated in CSS */
.picto-ds .picto-button {
  font: inherit;
  font-size: 11px;
  padding: 4px 10px;
  border: 1px solid #494949;
  border-radius: 4px;
  background: var(--picto-paper);
  color: var(--picto-ink);
  cursor: pointer;
}

.picto-ds .picto-button.active {
  background: var(--picto-ui-16);
  color: var(--picto-paper);
  border-color: var(--picto-ui-16);
}

.picto-ds .picto-statusbar {
  margin-top: 8px;
  font-size: 11px;
  color: var(--picto-chrome-gray);
  min-height: 1.2em;
}

.picto-ds .picto-toolbar {
  display: flex;
  gap: 6px;
  margin-top: 8px;
}

/* Page wrapper for guestbook */
.picto-ds.picto-page {
  min-height: 100vh;
  display: grid;
  place-items: center;
  background: #2b2b33;
  padding: 16px;
}

.picto-ds.picto-page.embed {
  min-height: auto;
  background: transparent;
  padding: 0;
}
`;

const componentsHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>picto-ds component gallery v0</title>
  <link rel="stylesheet" href="../../public/picto-ds/picto-ds.css"/>
  <style>
    body { margin: 0; background: #2b2b33; color: #e8e8ee; font-family: system-ui, sans-serif; }
    header { padding: 16px 20px; border-bottom: 1px solid #444; }
    .gallery { display: grid; gap: 32px; padding: 24px; }
    .sample { background: #3a3a44; border-radius: 8px; padding: 16px; }
    .sample h2 { margin: 0 0 12px; font-size: 14px; font-family: monospace; }
    .sample-desc { margin: 0 0 12px; font-size: 12px; color: #9a9aa4; }
  </style>
</head>
<body>
  <header>
    <h1>picto-ds.css v0 — component gallery</h1>
    <p>Generated by tools/sprites/generate-css.ts — ${swatchColors.length} UI swatch variables</p>
  </header>
  <div class="gallery">

    <section class="sample">
      <h2>.picto-shell</h2>
      <p class="sample-desc">Full DS frame: top screen + composer at 2× scale</p>
      <div class="picto-ds">
        <div class="picto-shell-frame">
          <div class="picto-shell">
            <section class="picto-screen-top">
              <img class="picto-screen-bg" src="../../public/picto-ds/sprites/screen-touch-striped-bg.png" alt=""/>
              <img class="picto-logo-bar" src="../../public/picto-ds/sprites/bar-pictochat-logo.png" alt="PictoChat"/>
              <img class="picto-entering-banner" src="../../public/picto-ds/sprites/banner-now-entering-black.png" alt=""/>
              <div class="picto-message-list"></div>
            </section>
            <section class="picto-composer">
              <img class="picto-composer-bg" src="../../public/picto-ds/sprites/composer-chrome-default.png" alt=""/>
              <canvas class="picto-canvas" width="228" height="79"></canvas>
              <img class="picto-keyboard" src="../../public/picto-ds/sprites/kbd-latin-main.png" alt=""/>
              <button type="button" class="picto-send-zone" aria-label="Send"></button>
            </section>
          </div>
        </div>
      </div>
    </section>

    <section class="sample">
      <h2>.picto-message-card</h2>
      <p class="sample-desc">White panel with nametag pill + 228×79 preview slot</p>
      <div class="picto-ds" style="--picto-scale:1">
        <article class="picto-message-card">
          <div class="picto-nametag">
            <img src="../../public/picto-ds/sprites/nametag-pill.png" alt=""/>
            <span class="picto-nametag-text">Player1</span>
          </div>
          <canvas class="picto-message-preview" width="228" height="79"></canvas>
        </article>
      </div>
    </section>

    <section class="sample">
      <h2>.picto-button + .picto-statusbar</h2>
      <div class="picto-ds">
        <div class="picto-toolbar">
          <button type="button" class="picto-button active">Pen</button>
          <button type="button" class="picto-button">Eraser</button>
        </div>
        <p class="picto-statusbar">Ready.</p>
      </div>
    </section>

    <section class="sample">
      <h2>UI palette (--picto-ui-01 … --picto-ui-16)</h2>
      <div class="picto-ds" style="display:flex;gap:4px;flex-wrap:wrap">
        ${swatchColors
          .map(
            (_, index) =>
              `<span style="width:24px;height:24px;background:var(--picto-ui-${String(index + 1).padStart(2, "0")});border:1px solid #494949" title="--picto-ui-${String(index + 1).padStart(2, "0")}"></span>`
          )
          .join("\n        ")}
      </div>
    </section>

  </div>
</body>
</html>
`;

await mkdir(path.dirname(CSS_OUT), { recursive: true });
await mkdir(path.dirname(COMPONENTS_OUT), { recursive: true });
await writeFile(CSS_OUT, css, "utf-8");
await writeFile(COMPONENTS_OUT, componentsHtml, "utf-8");

const cssBytes = Buffer.byteLength(css, "utf-8");
console.log(`Wrote ${CSS_OUT} (${cssBytes} bytes)`);
console.log(`Wrote ${COMPONENTS_OUT}`);
console.log(
  `Classes: picto-shell, picto-screen-top, picto-logo-bar, picto-entering-banner, picto-message-list, picto-message-card, picto-nametag, picto-composer, picto-canvas, picto-keyboard, picto-send-zone, picto-button, picto-statusbar`
);
console.log(`Swatch vars: --picto-ui-01 … --picto-ui-16`);
